### ISSUE TITLE
First batch of examples to test travis

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#70] opened 2020-04-02 10:10 UTC
The pull request must be adapted 
* for an identation with one tab (see https://gist.github.com/Protonk/3483490)
* The subdirectories for the xml-files need to be defined (currently subdirectory1 and subdirectory2 in examples
* The travis script works currently on the master branch. In SIRI we work on the integration branch, which is added to the master later. The group needs to define, what will be the workflow.
* Travis must be activated. Adrian tried to do it, but can't.  See https://travis-ci.com/. You go there and sign in with github. Then it should work.

`#!/bin/bash
/usr/bin/find . -name "*.xsd" -type f | while read i; do XMLLINT_INDENT=" " xmllint --pretty 1 "$i" > "$i.pretty"; mv "$i.pretty" "$i"; done; /usr/bin/find . -name "*.xml" -type f | while read i; do XMLLINT_INDENT=" " xmllint --pretty 1 "$i" > "$i.pretty"; mv "$i.pretty" "$i"; done; /usr/bin/find . -name "*.wsdl" -type f | while read i; do XMLLINT_INDENT=$"\t" xmllint --pretty 1 "$i" > "$i.pretty"; mv "$i.pretty" "$i"; done;
echo "finished formatting"
# xmllint --noout --schema OJP.xsd examples/subdirectory1/*xml examples/subdirectory2/*xml`

@haeckerbaer

**Comment by ue71603** [comment] 2020-04-02 10:12
For the activation @haeckerbaer said, tha one needs to be able to add travis in the organisation settings:
![image](https://user-images.githubusercontent.com/24227470/78237107-2bd10580-74db-11ea-805d-20c61021cd61.png)

**Comment by sgrossberndt** [comment] 2020-04-17 17:34
@haeckerbaer I have set up Travis and currently only allow Travis to push to the branch `travis_integration`
I have a successful build: https://travis-ci.com/github/VDVde/OJP/builds/160765382
but there are some problems:

- `travis-commit: failed to push git changes`
is shown in the build log (only visible when you expand the line 137)
Does Travis need additional permissions to be able to push?
- I would have expected the build to fail as there are formatting changes to the files which are not committed

Can you help here?

**Comment by sgrossberndt** [comment] 2020-04-20 10:14
We need to decide on a directory structure.
As we probably do not want to change the overall directory structure in v1.1 I propose to simply put them to `./examples`

**Comment by ue71603** [comment] 2020-04-20 10:41
Ok for me.

**Comment by sgrossberndt** [comment] 2020-04-21 15:19
Anyone willing to contribute some examples?

**Comment by pvgrumbkow** [comment] 2020-05-19 09:29
Can this issue be closed?

**Comment by sgrossberndt** [comment] 2020-05-19 09:38
No, as examples need to be integrated first in order to have a valid test by travis. Need to decide on https://github.com/VDVde/OJP/pull/75

**Comment by pvgrumbkow** [comment] 2020-05-20 13:28
OK. But in that case the title of the issue is misleading.

**Comment by sgrossberndt** [comment] 2020-05-20 13:29
This is the missing last part in the process of activating TRAVIS. Currently there will be no failures as no examples are there and nothing is tested yet.

**Comment by ue71603** [comment] 2020-05-23 14:32
New pull request created: https://github.com/VDVde/OJP/pull/85

**Comment by sgrossberndt** [comment] 2020-11-23 10:59
Fixed by #115

**Closed by sgrossberndt** 2020-11-23 10:59 UTC
