### ISSUE TITLE
Request for (more) documentation Siri:PtModeChoiceGroup is not imported in the documentation

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#161] opened 2021-06-16 15:17 UTC

**Comment by sgrossberndt** [comment] 2022-04-25 08:43
We already talked about that when generating the documentation.

The problem is we would need to render the SIRI source as documentation tables as well in order to be able to do this. The current state of the SIRI source is in no way fit to be doing this. Might be better with SIRI >=v2.1 but would still require a lot of work because we would not want to render the whole SIRI documentation but only those parts we use.

Another option would be if SIRI would have its own documentation and we could just link to it.

**Comment by ue71603** [comment] 2022-08-15 15:59
@skinkie  can we close this? We won't do it here, I guess.

**Comment by ue71603** [comment] 2022-12-06 17:41
Added some sentences to 8.3.5

**Closed by ue71603** 2022-12-06 17:41 UTC
Labels: documentation
